FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Copy essential files
COPY package.json package-lock.json turbo.json tsconfig.json ./

# Copy application and packages
COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
RUN npm install @prisma/client  # Explicitly install @prisma/client

# Generate Prisma client
RUN npx prisma generate

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "run", "start-user-app"]